print('Pizzas'.rjust(10))
print('----------')
print('Pepperoni'.rjust(10))
print('Margarhita'.rjust(10))
print('Hawaiian'.rjust(10))
print('Cheese'.rjust(10))

print()

print('Doughnuts'.ljust(11))
print('-----------'.ljust(11))
print('Cinammon'.ljust(11), end=' ')
print('[4]')
print('Sprinkles'.ljust(11), end=' ')
print('[6]')
print('Plain'.ljust(11), end=' ')
print('[X]')
print('Cream'.ljust(11), end=' ')
print('[3]')
print('Jelly'.ljust(11), end=' ')
print('[4]')

print()

print('Name'.center(10))
print('------'.center(10))
print('Toby'.center(10))
print('Mark'.center(10))
print('Peta'.center(10))
print('Bane'.center(10))

print()

print('Nugget')
print('Biscuit'.rjust(14))
print('Nugget in a biscuit'.center(20))
